"use client";

import { useEffect, useRef, useState } from "react";
import { Archive, BarChart3, CalendarDays, Check, CheckCircle2, Clock3, Home, MoreHorizontal, Plus, RotateCcw, Settings2, Sparkles, X } from "lucide-react";

type Priority = "urgent" | "high" | "medium" | "low";
type Status = "pending" | "completed" | "discarded";
type Task = { id:string; title:string; description?:string; categoryId?:string; priority:Priority; dueDate?:string; reminder?:string; icon:string; status:Status; createdAt:string; completedAt?:string; cycleTime?:number; completedOnTime?:boolean; snoozeCount:number; reopenedCount:number; discardedAt?:string };
type Category = { id:string; name:string; icon:string; color:string };

const categories: Category[] = [
  {id:"inbox",name:"Inbox",icon:"🧠",color:"#7357ff"},
  {id:"home",name:"Casa",icon:"🏠",color:"#15a77b"},
  {id:"work",name:"Trabajo",icon:"💼",color:"#2764ff"},
  {id:"teaching",name:"Docencia",icon:"📚",color:"#f59e0b"},
];
const now = new Date();
const isoAt = (h:number) => { const d=new Date(now); d.setHours(h,0,0,0); return d.toISOString(); };
const starter:Task[] = [
  {id:"1",title:"Enviar reporte semanal",categoryId:"work",priority:"urgent",dueDate:isoAt(11),reminder:"10m",icon:"📄",status:"pending",createdAt:new Date(now.getTime()-6*3600000).toISOString(),snoozeCount:0,reopenedCount:0},
  {id:"2",title:"Preparar mini examen",categoryId:"teaching",priority:"high",dueDate:isoAt(18),icon:"📚",status:"pending",createdAt:new Date(now.getTime()-86400000).toISOString(),snoozeCount:1,reopenedCount:0},
  {id:"3",title:"Comprar despensa",categoryId:"home",priority:"medium",icon:"🛒",status:"pending",createdAt:new Date(now.getTime()-2*86400000).toISOString(),snoozeCount:0,reopenedCount:0},
];
const pMeta={urgent:{label:"Urgente",color:"#ef4444"},high:{label:"Alta",color:"#f97316"},medium:{label:"Media",color:"#eab308"},low:{label:"Baja",color:"#22c55e"}};

function infer(title:string){ const s=title.toLowerCase(); if(/pagar|tarjeta|banco/.test(s)) return {icon:"💳",categoryId:"inbox"}; if(/comprar|despensa/.test(s)) return {icon:"🛒",categoryId:"home"}; if(/mazda|auto|servicio/.test(s)) return {icon:"🚗",categoryId:"home"}; if(/examen|clase|alumno/.test(s)) return {icon:"📚",categoryId:"teaching"}; if(/reporte|enviar|reunión/.test(s)) return {icon:"📄",categoryId:"work"}; return {icon:"✨",categoryId:"inbox"}; }
function timeLabel(value?:string){ if(!value) return "Sin fecha"; const d=new Date(value); const today=new Date(); if(d.toDateString()===today.toDateString()) return `Hoy · ${d.toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit"})}`; return d.toLocaleDateString("es-MX",{day:"numeric",month:"short"}); }

export default function TaskApp(){
  const [tasks,setTasks]=useState<Task[]>(starter); const [view,setView]=useState("home"); const [selectedCategory,setSelectedCategory]=useState<string|null>(null); const [ready,setReady]=useState(false); const [modal,setModal]=useState(false); const [title,setTitle]=useState(""); const [priority,setPriority]=useState<Priority>("medium"); const [category,setCategory]=useState("inbox"); const [due,setDue]=useState(""); const [toast,setToast]=useState<string|null>(null); const undo=useRef<Task|null>(null);
  useEffect(()=>{ const saved=localStorage.getItem("pendientes.tasks"); if(saved) try{setTasks(JSON.parse(saved))}catch{} setReady(true); if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js"); },[]);
  useEffect(()=>{if(ready)localStorage.setItem("pendientes.tasks",JSON.stringify(tasks))},[tasks,ready]);
  const pending=tasks.filter(t=>t.status==="pending"); const completed=tasks.filter(t=>t.status==="completed");
  const showToast=(s:string)=>{setToast(s);setTimeout(()=>setToast(null),3200)};
  const complete=(task:Task)=>{ const completedAt=new Date().toISOString(); const done={...task,status:"completed" as Status,completedAt,cycleTime:new Date(completedAt).getTime()-new Date(task.createdAt).getTime(),completedOnTime:task.dueDate?new Date(completedAt)<=new Date(task.dueDate):undefined}; undo.current=task; setTasks(x=>x.map(t=>t.id===task.id?done:t)); showToast("Actividad completada"); };
  const snooze=(task:Task)=>{ const d=new Date(Date.now()+3600000).toISOString(); setTasks(x=>x.map(t=>t.id===task.id?{...t,dueDate:d,snoozeCount:t.snoozeCount+1}:t)); showToast("Pospuesta 1 hora"); };
  const add=()=>{if(!title.trim())return; const guess=infer(title); const t:Task={id:crypto.randomUUID(),title:title.trim(),categoryId:category||guess.categoryId,priority,dueDate:due?new Date(due).toISOString():undefined,icon:guess.icon,status:"pending",createdAt:new Date().toISOString(),snoozeCount:0,reopenedCount:0}; setTasks(x=>[t,...x]);setTitle("");setDue("");setModal(false);showToast("Pendiente agregado")};
  const todayDone=completed.filter(t=>new Date(t.completedAt!).toDateString()===now.toDateString()).length;
  const overdue=pending.filter(t=>t.dueDate&&new Date(t.dueDate)<new Date()).length;

  return <main className="min-h-[100dvh] bg-[#f4f7fb] text-[#172034] pb-28">
    <div className="mx-auto min-h-[100dvh] max-w-[680px] bg-[#f8faff] shadow-[0_0_70px_rgba(44,72,130,.09)]">
      <header className="px-5 pt-7 pb-4 sm:px-8"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-[#72809a]">MIÉRCOLES, 2 SEP</p><h1 className="mt-1 text-[2rem] font-extrabold tracking-[-.04em]">Hola, Christian <span aria-hidden>👋</span></h1></div><button aria-label="Configuración" className="grid size-11 place-items-center rounded-2xl bg-white text-[#52617a] shadow-sm" onClick={()=>setView("settings")}><Settings2 size={21}/></button></div></header>
      <div className="px-5 sm:px-8"><button onClick={()=>setModal(true)} className="flex w-full items-center gap-3 rounded-[1.25rem] border border-[#e5eaf3] bg-white px-4 py-4 text-left shadow-[0_8px_28px_rgba(41,61,105,.07)]"><span className="grid size-9 place-items-center rounded-xl bg-[#edf2ff] text-[#2764ff]"><Plus size={20}/></span><span className="flex-1 text-[15px] font-semibold text-[#72809a]">¿Qué tienes en mente?</span><Sparkles size={18} className="text-[#7657ff]"/></button></div>
      {view==="home"&&<div className="px-5 sm:px-8">
        <section className="mt-6 grid grid-cols-3 gap-3"><Stat n={pending.length} label="Pendientes" tone="#2764ff"/><Stat n={todayDone} label="Hechas hoy" tone="#16a47a"/><Stat n={overdue} label="Vencidas" tone="#ef4444"/></section>
        <section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold tracking-tight">Prioridad ahora</h2><button className="text-sm font-bold text-[#2764ff]" onClick={()=>setView("agenda")}>Ver agenda</button></div><div className="mt-4 space-y-3">{pending.slice(0,3).map(t=><TaskCard key={t.id} task={t} onComplete={()=>complete(t)} onSnooze={()=>snooze(t)} />)}{!pending.length&&<Empty/>}</div></section>
        <section className="mt-8"><h2 className="text-xl font-extrabold tracking-tight">Categorías</h2><div className="mt-4 grid grid-cols-2 gap-3">{categories.slice(0,4).map(c=><button key={c.id} onClick={()=>{setSelectedCategory(c.id);setView("category")}} aria-label={`Ver pendientes de ${c.name}`} className="flex items-center gap-3 rounded-[1.25rem] bg-white p-4 text-left shadow-sm transition active:scale-[.98]"><span className="grid size-11 place-items-center rounded-2xl text-xl" style={{background:c.color+"18"}}>{c.icon}</span><span className="min-w-0 flex-1"><b className="block truncate text-[15px]">{c.name}</b><small className="text-[#8590a5]">{pending.filter(t=>t.categoryId===c.id).length} pendientes</small></span><span className="text-[#a6afbf]">›</span></button>)}</div></section>
      </div>}
      {view==="category"&&selectedCategory&&(()=>{const c=categories.find(x=>x.id===selectedCategory)!;const items=pending.filter(t=>t.categoryId===selectedCategory);return <section className="px-5 pt-7 sm:px-8"><button onClick={()=>setView("home")} className="mb-5 flex items-center gap-2 text-sm font-bold text-[#2764ff]"><span aria-hidden>←</span> Inicio</button><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-[1.2rem] text-2xl" style={{background:c.color+"18"}}>{c.icon}</span><div><h2 className="text-3xl font-extrabold tracking-[-.035em]">{c.name}</h2><p className="mt-1 text-[#78859a]">{items.length} {items.length===1?"pendiente":"pendientes"}</p></div></div><div className="mt-6 space-y-3">{items.map(t=><TaskCard key={t.id} task={t} onComplete={()=>complete(t)} onSnooze={()=>snooze(t)}/>)}{!items.length&&<Empty/>}</div></section>})()}
      {view==="agenda"&&<Page title="Agenda" subtitle="Lo que viene"><div className="space-y-3">{pending.map(t=><TaskCard key={t.id} task={t} onComplete={()=>complete(t)} onSnooze={()=>snooze(t)}/>)}</div></Page>}
      {view==="insights"&&<Page title="Esta semana" subtitle="Tu ritmo, sin juicios"><div className="grid grid-cols-2 gap-3"><Insight icon="✅" value={completed.length} label="Completadas"/><Insight icon="⏱" value={completed.length?Math.round(completed.reduce((a,t)=>a+(t.cycleTime||0),0)/completed.length/3600000)+" h":"—"} label="Tiempo promedio"/><Insight icon="🎯" value={completed.length?Math.round(100*completed.filter(t=>t.completedOnTime!==false).length/completed.length)+" %":"—"} label="A tiempo"/><Insight icon="🔄" value={tasks.reduce((a,t)=>a+t.snoozeCount,0)} label="Posposiciones"/></div><div className="mt-6 rounded-[1.5rem] bg-[#172034] p-5 text-white"><p className="text-sm text-white/60">Lectura rápida</p><h3 className="mt-2 text-xl font-bold">{completed.length?"Estás creando impulso.":"Completa tu primera actividad."}</h3><p className="mt-2 text-sm leading-6 text-white/70">Aquí aparecerán tendencias por categoría, prioridad y semana conforme uses la app.</p></div></Page>}
      {view==="history"&&<Page title="Historial" subtitle={`${completed.length} actividades completadas`}><div className="space-y-3">{completed.map(t=><article key={t.id} className="flex items-center gap-3 rounded-2xl bg-white p-4"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-lg">{t.icon}</span><div className="min-w-0 flex-1"><p className="truncate font-semibold">{t.title}</p><p className="text-sm text-[#8390a5]">Completada · {t.cycleTime?Math.max(1,Math.round(t.cycleTime/3600000))+" h":"ahora"}</p></div><button aria-label="Reabrir" onClick={()=>setTasks(x=>x.map(a=>a.id===t.id?{...a,status:"pending",completedAt:undefined,cycleTime:undefined,reopenedCount:a.reopenedCount+1}:a))}><RotateCcw size={18}/></button></article>)}</div></Page>}
      {view==="settings"&&<Page title="Configuración" subtitle="Tu espacio, a tu manera"><div className="rounded-2xl bg-white p-5"><h3 className="font-bold">Datos locales</h3><p className="mt-2 text-sm leading-6 text-[#718096]">Tus pendientes se guardan en este dispositivo. La sincronización entre dispositivos llegará en una siguiente versión.</p></div></Page>}
    </div>
    <nav className="fixed inset-x-0 bottom-0 z-30 mx-auto flex max-w-[680px] items-center justify-around border-t border-[#e7ebf2] bg-white/95 px-3 pb-[max(12px,env(safe-area-inset-bottom))] pt-2 backdrop-blur"><Nav active={view==="home"} icon={<Home/>} label="Inicio" onClick={()=>setView("home")}/><Nav active={view==="agenda"} icon={<CalendarDays/>} label="Agenda" onClick={()=>setView("agenda")}/><button onClick={()=>setModal(true)} aria-label="Crear pendiente" className="-mt-8 grid size-15 place-items-center rounded-[1.35rem] bg-[#2764ff] text-white shadow-[0_10px_25px_rgba(39,100,255,.38)]"><Plus size={29}/></button><Nav active={view==="insights"} icon={<BarChart3/>} label="Insights" onClick={()=>setView("insights")}/><Nav active={view==="history"} icon={<Archive/>} label="Historial" onClick={()=>setView("history")}/></nav>
    {modal&&<div className="fixed inset-0 z-40 bg-[#101828]/45 backdrop-blur-sm" onClick={()=>setModal(false)}><section className="absolute inset-x-0 bottom-0 mx-auto max-w-[680px] rounded-t-[2rem] bg-white p-5 pb-[max(24px,env(safe-area-inset-bottom))]" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-5 h-1.5 w-11 rounded-full bg-[#dfe4ed]"/><div className="flex items-center justify-between"><h2 className="text-2xl font-extrabold">Nuevo pendiente</h2><button onClick={()=>setModal(false)} className="grid size-10 place-items-center rounded-xl bg-[#f2f4f8]"><X size={20}/></button></div><div className="mt-5 rounded-2xl bg-[#f5f7fb] p-4"><textarea autoFocus value={title} onChange={e=>{setTitle(e.target.value);const g=infer(e.target.value);setCategory(g.categoryId)}} placeholder="Escribe lo que necesitas hacer…" className="min-h-20 w-full resize-none bg-transparent text-lg font-semibold outline-none"/>{title&&<p className="text-sm text-[#7657ff]">{infer(title).icon} Icono sugerido automáticamente</p>}</div><div className="mt-4 grid grid-cols-2 gap-3"><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-2xl border border-[#e3e8f0] bg-white p-3 font-semibold">{categories.map(c=><option key={c.id} value={c.id}>{c.icon} {c.name}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value as Priority)} className="rounded-2xl border border-[#e3e8f0] bg-white p-3 font-semibold">{Object.entries(pMeta).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></div><input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)} className="mt-3 w-full rounded-2xl border border-[#e3e8f0] p-3"/><button onClick={add} disabled={!title.trim()} className="mt-5 w-full rounded-2xl bg-[#2764ff] py-4 font-bold text-white disabled:opacity-40">Agregar pendiente</button></section></div>}
    {toast&&<div className="fixed bottom-24 left-1/2 z-50 flex -translate-x-1/2 items-center gap-3 rounded-2xl bg-[#172034] px-4 py-3 text-sm font-semibold text-white shadow-xl"><CheckCircle2 size={19} className="text-emerald-400"/>{toast}{undo.current&&toast.includes("completada")&&<button className="text-[#8fb0ff]" onClick={()=>{setTasks(x=>x.map(t=>t.id===undo.current!.id?undo.current!:t));undo.current=null;setToast(null)}}>Deshacer</button>}</div>}
  </main>
}

function TaskCard({task,onComplete,onSnooze}:{task:Task;onComplete:()=>void;onSnooze:()=>void}){ const start=useRef(0); const [dx,setDx]=useState(0); const cat=categories.find(c=>c.id===task.categoryId); return <div className="relative overflow-hidden rounded-[1.4rem] bg-[#dff7ed]"><div className="absolute inset-y-0 left-4 flex items-center gap-2 font-bold text-emerald-700"><Check/> Completar</div><div className="absolute inset-y-0 right-4 flex items-center gap-2 font-bold text-amber-700">Posponer <Clock3/></div><article style={{transform:`translateX(${dx}px)`}} onPointerDown={e=>{start.current=e.clientX;(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(start.current)setDx(Math.max(-110,Math.min(110,e.clientX-start.current)))}} onPointerUp={()=>{if(dx>70)onComplete();else if(dx<-70)onSnooze();setDx(0);start.current=0}} className="relative flex touch-pan-y items-center gap-3 rounded-[1.4rem] bg-white p-4 shadow-[0_6px_24px_rgba(36,54,96,.07)] transition-transform"><span className="grid size-12 shrink-0 place-items-center rounded-2xl text-2xl" style={{background:(cat?.color||"#2764ff")+"15"}}>{task.icon}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="size-2 rounded-full" style={{background:pMeta[task.priority].color}}/><span className="text-xs font-bold uppercase tracking-wide" style={{color:pMeta[task.priority].color}}>{pMeta[task.priority].label}</span></div><h3 className="mt-1 truncate text-[16px] font-bold">{task.title}</h3><p className="mt-1 flex items-center gap-2 text-sm text-[#7d899e]"><span>{cat?.icon} {cat?.name}</span><span>•</span><Clock3 size={14}/>{timeLabel(task.dueDate)}</p></div><button aria-label="Más opciones" className="self-start text-[#9aa4b5]"><MoreHorizontal size={21}/></button></article></div> }
function Stat({n,label,tone}:{n:number;label:string;tone:string}){return <div className="rounded-[1.2rem] bg-white p-3 shadow-sm"><b className="block text-2xl" style={{color:tone}}>{n}</b><span className="text-xs font-semibold text-[#8290a6]">{label}</span></div>}
function Nav({active,icon,label,onClick}:{active:boolean;icon:React.ReactNode;label:string;onClick:()=>void}){return <button onClick={onClick} className={`flex min-w-14 flex-col items-center gap-1 text-[11px] font-bold ${active?"text-[#2764ff]":"text-[#8b96aa]"}`}><span className="[&>svg]:size-5">{icon}</span>{label}</button>}
function Page({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="px-5 pt-7 sm:px-8"><h2 className="text-3xl font-extrabold tracking-[-.035em]">{title}</h2><p className="mt-1 mb-6 text-[#78859a]">{subtitle}</p>{children}</section>}
function Insight({icon,value,label}:{icon:string;value:string|number;label:string}){return <div className="rounded-[1.4rem] bg-white p-5 shadow-sm"><span className="text-2xl">{icon}</span><b className="mt-4 block text-3xl tracking-tight">{value}</b><span className="text-sm text-[#7d899d]">{label}</span></div>}
function Empty(){return <div className="rounded-[1.4rem] border border-dashed border-[#ced7e8] p-7 text-center"><span className="text-3xl">✨</span><h3 className="mt-2 font-bold">Todo en orden</h3><p className="mt-1 text-sm text-[#7c899e]">Tu lista está despejada.</p></div>}
